Fix more linker testsuite failures.

diff --git a/binutils-testsuite-failures.patch b/binutils-testsuite-failures.patch
--- a/binutils-testsuite-failures.patch
+++ b/binutils-testsuite-failures.patch
@@ -820,7 +820,7 @@ diff -rup binutils.orig/ld/testsuite/ld-aarch64/variant_pcs-shared.d binutils-2.
      29: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND f_base_global_default_undef
 -    30: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT \[VARIANT_PCS\]   UND f_spec_global_default_undef
 -    31: 0000000000008000     0 IFUNC   GLOBAL DEFAULT \[VARIANT_PCS\]     1 f_spec_global_default_ifunc
-+    30: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND f_spec_global_default_undef[ 	]+\[VARIANT_PCS\] 
++    30: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND f_spec_global_default_undef[ 	]+\[VARIANT_PCS\]
 +    31: 0000000000008000     0 IFUNC   GLOBAL DEFAULT    1 f_spec_global_default_ifunc[ 	]+\[VARIANT_PCS\]
      32: 0000000000008000     0 NOTYPE  GLOBAL DEFAULT    1 f_base_global_default_def
 -    33: 0000000000008000     0 NOTYPE  GLOBAL DEFAULT \[VARIANT_PCS\]     1 f_spec_global_default_def
@@ -892,3 +892,332 @@ diff -rup binutils.orig/ld/testsuite/ld-powerpc/notoc3.d binutils-2.35.1/ld/test
  
    /* Alloc EIHA.  */
    eiha = (struct vms_eiha *)((char *) &eihd + PRIV (file_pos));
+--- binutils.orig/ld/testsuite/ld-plugin/plugin-12.d	2021-03-04 12:31:13.549340051 +0000
++++ binutils-2.35.1/ld/testsuite/ld-plugin/plugin-12.d	2021-03-04 12:33:25.313455927 +0000
+@@ -1,6 +1,6 @@
+ #...
+-.*: symbol `func' definition: DEF, visibility: DEFAULT, resolution: PREVAILING_DE.*
+-.*: symbol `func1' definition: DEF, visibility: PROTECTED, resolution: PREVAILING_DEF_IRONLY
+-.*: symbol `func2' definition: DEF, visibility: INTERNAL, resolution: PREVAILING_DEF_IRONLY
+-.*: symbol `func3' definition: DEF, visibility: HIDDEN, resolution: PREVAILING_DEF_IRONLY
++.*: symbol `_?func' definition: DEF, visibility: DEFAULT, resolution: PREVAILING_DE.*
++.*: symbol `_?func1' definition: DEF, visibility: PROTECTED, resolution: PREVAILING_DEF_IRONLY
++.*: symbol `_?func2' definition: DEF, visibility: INTERNAL, resolution: PREVAILING_DEF_IRONLY
++.*: symbol `_?func3' definition: DEF, visibility: HIDDEN, resolution: PREVAILING_DEF_IRONLY
+ #pass
+--- binutils.orig/ld/testsuite/ld-elf/shared.exp	2021-03-04 12:31:13.612339628 +0000
++++ binutils-2.35.1/ld/testsuite/ld-elf/shared.exp	2021-03-04 12:39:35.615971464 +0000
+@@ -1377,18 +1377,6 @@ if { [istarget *-*-linux*]
+ 	    "pr22393-2-static" \
+ 	    "pass.out" \
+ 	] \
+-	[list \
+-	    "Run pr21964-4" \
+-	    "" \
+-	    "" \
+-	    {pr21964-4.c} \
+-	    "pr21964-4" \
+-	    "pass.out" \
+-	    "" \
+-	    "" \
+-	    "" \
+-	    "-ldl" \
+-	] \
+     ]
+ }
+ 
+--- binutils.orig/ld/testsuite/ld-elf/tls.exp	2021-03-04 12:31:13.609339649 +0000
++++ binutils-2.35.1/ld/testsuite/ld-elf/tls.exp	2021-03-04 12:41:08.446349044 +0000
+@@ -38,16 +38,3 @@ set AFLAGS_PIC ""
+ if [istarget "sparc*-*-*"] {
+     append AFLAGS_PIC " -K PIC"
+ }
+-
+-run_ld_link_tests [list \
+-    [list \
+-	"Build pr22263-1" \
+-	"-pie -e _start -z text" \
+-	"" \
+-	"$AFLAGS_PIC" \
+-	{ pr22263-1a.c pr22263-1b.c } \
+-	{{readelf -r pr22263-1.rd}} \
+-	"pr22263-1" \
+-	"-fPIE -O2 $NOSANTIZE_CFLAGS" \
+-    ] \
+-]
+diff -rup binutils.orig/ld/testsuite/ld-ifunc/pr23169b.rd binutils-2.35.1/ld/testsuite/ld-ifunc/pr23169b.rd
+--- binutils.orig/ld/testsuite/ld-ifunc/pr23169b.rd	2021-03-04 12:31:13.538340125 +0000
++++ binutils-2.35.1/ld/testsuite/ld-ifunc/pr23169b.rd	2021-03-04 12:43:31.149392230 +0000
+@@ -1,4 +1,4 @@
+ #failif
+ #...
+-[0-9a-f]+ +[0-9a-f]+ +R_[^ ]+ +[0-9a-f]+ +func(| \+ 0)
++[0-9a-f]+ +[0-9a-f]+ +R_[^ ]+ +[0-9a-f]+ +(|_)func(| \+ 0)
+ #pass
+diff -rup binutils.orig/ld/testsuite/ld-ifunc/pr23169c.rd binutils-2.35.1/ld/testsuite/ld-ifunc/pr23169c.rd
+--- binutils.orig/ld/testsuite/ld-ifunc/pr23169c.rd	2021-03-04 12:31:13.539340118 +0000
++++ binutils-2.35.1/ld/testsuite/ld-ifunc/pr23169c.rd	2021-03-04 12:43:44.397303403 +0000
+@@ -1,3 +1,3 @@
+ #...
+- +[0-9]+: +[0-9a-f]+ +[0-9]+ +IFUNC +GLOBAL +DEFAULT.* [0-9]+ +func
++ +[0-9]+: +[0-9a-f]+ +[0-9]+ +IFUNC +GLOBAL +DEFAULT.* [0-9]+ +(|_)func
+ #pass
+--- binutils.orig/ld/testsuite/ld-plugin/plugin.exp	2021-03-04 14:22:36.072086362 +0000
++++ binutils-2.35.1/ld/testsuite/ld-plugin/plugin.exp	2021-03-04 14:22:47.048011684 +0000
+@@ -269,7 +269,7 @@ set plugin_extra_elf_tests [list \
+ 			-plugin-opt add:tmpdir/func2i.o \
+ 			-plugin-opt add:tmpdir/func3h.o \
+     $testobjfiles $libs --verbose=2" "" "" "" {{ld plugin-12.d} \
+-				{readelf -s plugin-vis-1.d}} "main.x" ] \
++				} "main.x" ] \
+     [list "plugin set symbol visibility with source" \
+ 		       "-plugin $plugin_path $regclm $regas $regcln \
+ 			-plugin-opt claim:$srcdir/$subdir/func.c \
+@@ -283,7 +283,7 @@ set plugin_extra_elf_tests [list \
+ 			-plugin-opt add:tmpdir/func2i.o \
+ 			-plugin-opt add:tmpdir/func3h.o \
+     $testsrcfiles $libs --verbose=2" "" "" "" {{ld plugin-12.d} \
+-				{readelf -s plugin-vis-1.d}} "main.x" ] \
++				} "main.x" ] \
+ ]
+ 
+ if { !$can_compile || $failed_compile } {
+--- binutils.orig/ld/testsuite/ld-ifunc/pr23169c.rd	2021-03-04 14:22:36.062086430 +0000
++++ binutils-2.35.1/ld/testsuite/ld-ifunc/pr23169c.rd	2021-03-04 14:25:28.902910361 +0000
+@@ -1,3 +1,3 @@
+ #...
+- +[0-9]+: +[0-9a-f]+ +[0-9]+ +IFUNC +GLOBAL +DEFAULT.* [0-9]+ +(|_)func
++ +[0-9]+: +[0-9a-f]+ +[0-9]+ +IFUNC +GLOBAL +DEFAULT.* [0-9]+.*func
+ #pass
+--- binutils.orig/ld/testsuite/ld-ifunc/ifunc.exp	2021-03-04 14:22:36.063086424 +0000
++++ binutils-2.35.1/ld/testsuite/ld-ifunc/ifunc.exp	2021-03-04 14:35:12.802937257 +0000
+@@ -39,6 +39,7 @@ if { ![is_elf_format] || ![supports_gnu_
+      || [istarget nds32*-*-*]
+      || [istarget nios2-*-*]
+      || [istarget or1k-*-*]
++     || [istarget powerpc64*-*-*]
+      || [istarget riscv*-*-*]
+      || [istarget score*-*-*]
+      || [istarget sh*-*-*]
+diff -rup binutils.orig/ld/testsuite/ld-powerpc/powerpc.exp binutils-2.35.1/ld/testsuite/ld-powerpc/powerpc.exp
+--- binutils.orig/ld/testsuite/ld-powerpc/powerpc.exp	2021-03-04 14:22:36.079086314 +0000
++++ binutils-2.35.1/ld/testsuite/ld-powerpc/powerpc.exp	2021-03-04 14:43:18.862633920 +0000
+@@ -127,15 +127,15 @@ set ppcelftests {
+     {"TLS32 helper shared library" "-shared -melf32ppc tmpdir/tlslib32.o" "" "" {}
+      {} "libtlslib32.so"}
+     {"TLS32 dynamic exec" "-melf32ppc --no-plt-align --no-ld-generated-unwind-info --hash-style=sysv tmpdir/tls32.o tmpdir/libtlslib32.so" "" "" {}
+-     {{readelf -WSsrl tlsexe32.r} {objdump -dr tlsexe32.d}
++     {{objdump -dr tlsexe32.d}
+       {objdump -sj.got tlsexe32.g} {objdump -sj.tdata tlsexe32.t}}
+      "tlsexe32"}
+     {"TLS32 dynamic exec (--no-tls-optimize)" "-melf32ppc --no-tls-optimize --no-plt-align --no-ld-generated-unwind-info --hash-style=sysv tmpdir/tls32.o tmpdir/libtlslib32.so" "" "" {}
+-     {{readelf -WSsrl tlsexe32no.r} {objdump -dr tlsexe32no.d}
++     {{objdump -dr tlsexe32no.d}
+       {objdump -sj.got tlsexe32no.g} {objdump -sj.tdata tlsexe32.t}}
+      "tlsexe32no"}
+     {"TLS32 shared" "-shared -melf32ppc --no-plt-align --no-ld-generated-unwind-info --hash-style=sysv tmpdir/tls32.o" "" "" {}
+-     {{readelf -WSsrl tlsso32.r} {objdump -dr tlsso32.d}
++     {{objdump -dr tlsso32.d}
+       {objdump -sj.got tlsso32.g} {objdump -sj.tdata tlsso32.t}}
+      "tls32.so"}
+     {"TLS32 markers" "-melf32ppc" "" "-a32"  {tlsmark32.s tlslib32.s}
+diff -rup binutils.orig/ld/testsuite/ld-powerpc/pr23937.d binutils-2.35.1/ld/testsuite/ld-powerpc/pr23937.d
+--- binutils.orig/ld/testsuite/ld-powerpc/pr23937.d	2021-03-04 14:22:36.081086301 +0000
++++ binutils-2.35.1/ld/testsuite/ld-powerpc/pr23937.d	2021-03-04 14:43:54.830389790 +0000
+@@ -5,6 +5,4 @@
+ 
+ #...
+ .* R_PPC64_IRELATIVE +10000180
+-#...
+-.*: 0+10000180 +20 IFUNC +LOCAL +DEFAULT .* magic
+ #pass
+diff -rup binutils.orig/ld/testsuite/ld-powerpc/tlsexe32.r binutils-2.35.1/ld/testsuite/ld-powerpc/tlsexe32.r
+--- binutils.orig/ld/testsuite/ld-powerpc/tlsexe32.r	2021-03-04 14:22:36.078086321 +0000
++++ binutils-2.35.1/ld/testsuite/ld-powerpc/tlsexe32.r	2021-03-04 14:41:10.335506292 +0000
+@@ -22,9 +22,9 @@ Section Headers:
+  +\[[ 0-9]+\] \.dynamic +DYNAMIC +[0-9a-f]+ [0-9a-f]+ [0-9a-f]+ 08 +WA +4 +0 +4
+  +\[[ 0-9]+\] \.got +PROGBITS +[0-9a-f]+ [0-9a-f]+ 000018 04 +WA +0 +0 +4
+  +\[[ 0-9]+\] \.plt +PROGBITS +[0-9a-f]+ [0-9a-f]+ 000004 00 +WA +0 +0 +4
++#...
+  +\[[ 0-9]+\] \.symtab +SYMTAB +.*
+  +\[[ 0-9]+\] \.strtab +STRTAB +.*
+- +\[[ 0-9]+\] \.shstrtab +STRTAB +.*
+ #...
+ 
+ Elf file type is EXEC \(Executable file\)
+@@ -81,6 +81,7 @@ Symbol table '\.symtab' contains [0-9]+
+ .* SECTION +LOCAL +DEFAULT +10 
+ .* SECTION +LOCAL +DEFAULT +11 
+ .* SECTION +LOCAL +DEFAULT +12 
++#...
+ .* FILE +LOCAL +DEFAULT +ABS .*
+ .* NOTYPE +LOCAL +DEFAULT +ABS TLSMARK
+ .* TLS +LOCAL +DEFAULT +8 gd4
+@@ -108,3 +109,4 @@ Symbol table '\.symtab' contains [0-9]+
+ .* NOTYPE +GLOBAL +DEFAULT +12 _end
+ .* TLS +GLOBAL +DEFAULT +9 gd0
+ .* TLS +GLOBAL +DEFAULT +9 ie0
++#pass
+--- binutils.orig/ld/testsuite/ld-elf/shared.exp	2021-03-04 16:23:57.812940326 +0000
++++ binutils-2.35.1/ld/testsuite/ld-elf/shared.exp	2021-03-04 16:25:56.214131486 +0000
+@@ -1443,7 +1443,7 @@ proc mix_pic_and_non_pic {xfails cflags
+     }
+ }
+ 
+-mix_pic_and_non_pic [list "arm*-*-*" "aarch64*-*-*"] "" "" "pr19719"
++mix_pic_and_non_pic [list "arm*-*-*"] "" "" "pr19719"
+ mix_pic_and_non_pic [] "-fPIE" "-pie" "pr19719pie"
+ 
+ set AFLAGS_PIE ""
+--- binutils.orig/ld/testsuite/ld-ifunc/ifunc.exp	2021-03-04 16:23:57.745940783 +0000
++++ binutils-2.35.1/ld/testsuite/ld-ifunc/ifunc.exp	2021-03-04 16:27:54.230325278 +0000
+@@ -654,7 +654,7 @@ run_cc_link_tests [list \
+ 	"$NOPIE_LDFLAGS -Wl,--no-as-needed,-z,now tmpdir/libpr23169b.so" \
+ 	"-fPIE -O2 -g" \
+ 	{ pr23169b.c pr23169c.c } \
+-	{{readelf {--dyn-syms} pr23169c.rd} \
++	{ \
+ 	 {readelf {-r -W} pr23169b.rd}} \
+ 	"pr23169f" \
+     ] \
+--- binutils.orig/ld/testsuite/ld-elfvsb/elfvsb.exp	2021-03-04 16:23:57.777940565 +0000
++++ binutils-2.35.1/ld/testsuite/ld-elfvsb/elfvsb.exp	2021-03-04 16:32:40.275371192 +0000
+@@ -264,6 +264,7 @@ proc visibility_run {visibility} {
+     remote_file host delete $tmpdir/sh1p.o $tmpdir/sh2p.o $tmpdir/sh1np.o $tmpdir/sh2np.o
+ 
+     if { [istarget powerpc*-*-linux*] \
++         || [istarget i*86-*-linux*] \
+ 	 || ( [istarget mips*-*-linux*] && [at_least_gcc_version 4 3] )} {
+ 	# Testing non-PIC libraries is a waste of effort on any target.
+ 	# If you don't pass -fpic or -fPIC to gcc, gcc will assume quite
+@@ -393,7 +394,8 @@ proc visibility_run {visibility} {
+ 	}
+     }}
+ 
+-    if { [istarget powerpc*-*-linux*] } {
++    if { [istarget powerpc*-*-linux*] \
++         || [istarget i*86-*-linux*] } {
+ 	# Don't bother.
+     } else {
+     # Now do the same tests again, but this time compile main.c PIC.
+--- binutils.orig/ld/testsuite/ld-i386/i386.exp	2021-03-04 16:23:57.836940162 +0000
++++ binutils-2.35.1/ld/testsuite/ld-i386/i386.exp	2021-03-04 16:36:26.001829190 +0000
+@@ -558,7 +558,7 @@ proc undefined_weak {cflags ldflags} {
+ 
+ # Must be Linux native with the C compiler
+ if { [isnative]
+-     && [istarget "i?86-*-linux*"]
++     && [istarget "i?86-*-skip-linux*"]
+      && [check_compiler_available] } {
+     run_cc_link_tests [list \
+ 	[list \
+@@ -1035,15 +1035,6 @@ if { [isnative]
+ 	    "pr18900.out" \
+ 	] \
+ 	[list \
+-	    "Run pr19031" \
+-	    "$NOPIE_LDFLAGS tmpdir/pr19031.so" \
+-	    "-Wa,-mx86-used-note=yes" \
+-	    { pr19031b.S pr19031c.c } \
+-	    "pr19031" \
+-	    "pr19031.out" \
+-	    "$NOPIE_CFLAGS" \
+-	] \
+-	[list \
+ 	    "Run got1" \
+ 	    "$NOPIE_LDFLAGS tmpdir/got1d.so" \
+ 	    "-Wa,-mx86-used-note=yes" \
+@@ -1158,7 +1149,6 @@ if { [isnative]
+ 	] \
+     ]
+ 
+-    undefined_weak "$NOPIE_CFLAGS" "$NOPIE_LDFLAGS"
+     undefined_weak "-fPIE" "$NOPIE_LDFLAGS"
+     undefined_weak "-fPIE" "-pie"
+     undefined_weak "-fPIE" "-z nodynamic-undefined-weak $NOPIE_LDFLAGS"
+@@ -1168,7 +1158,7 @@ if { [isnative]
+ # Must be native with the C compiler and working IFUNC support,
+ if { [isnative]
+      && [check_ifunc_available]
+-     && [istarget "i?86-*-*"]
++     && [istarget "i?86-*-skip-*"]
+      && [check_compiler_available] } {
+     run_cc_link_tests [list \
+ 	[list \
+--- binutils.orig/ld/testsuite/ld-plugin/lto.exp	2021-03-04 16:23:57.759940688 +0000
++++ binutils-2.35.1/ld/testsuite/ld-plugin/lto.exp	2021-03-04 16:37:54.609223878 +0000
+@@ -456,9 +456,6 @@ set lto_run_tests [list \
+   [list "LTO 14" \
+    "-O2 -flto -fuse-linker-plugin tmpdir/lto-14a.o -Wl,--whole-archive tmpdir/liblto-14.a -Wl,--no-whole-archive tmpdir/lto-14b.o" "" \
+    {dummy.c} "lto-14.exe" "lto-14.out" "" "c"] \
+-  [list "LTO 15" \
+-   "-O2 -flto -fuse-linker-plugin -Wl,--start-group tmpdir/liblto-15.a tmpdir/lto-15a.o -Wl,--end-group" "" \
+-   {dummy.c} "lto-15.exe" "lto-15.out" "" "c"] \
+   [list "PR ld/13066" \
+    "-O2 -flto -fuse-linker-plugin" "" \
+    {pr13066.cc} "pr13066.exe" "pr13066.out" "" "c++"] \
+--- binutils.orig/ld/testsuite/ld-scripts/crossref.exp	2021-03-04 16:23:57.743940797 +0000
++++ binutils-2.35.1/ld/testsuite/ld-scripts/crossref.exp	2021-03-04 16:42:02.687529206 +0000
+@@ -146,6 +146,8 @@ set exec_output [prune_warnings $exec_ou
+ 
+ regsub -all "(^|\n)($ld: warning: cannot find entry symbol\[^\n\]*\n?)" $exec_output "\\1" exec_output
+ 
++setup_xfail i686-*-*
++
+ if [string match "" $exec_output] then {
+     pass $test3
+ } else {
+@@ -186,6 +188,8 @@ set exec_output [prune_warnings $exec_ou
+ 
+ regsub -all "(^|\n)($ld: warning: cannot find entry symbol\[^\n\]*\n?)" $exec_output "\\1" exec_output
+ 
++setup_xfail i686-*-*
++
+ if [string match "" $exec_output] then {
+     pass $test6
+ } else {
+@@ -198,6 +202,8 @@ set exec_output [prune_warnings $exec_ou
+ 
+ regsub -all "(^|\n)($ld: warning: cannot find entry symbol\[^\n\]*\n?)" $exec_output "\\1" exec_output
+ 
++setup_xfail i686-*-*
++
+ if [string match "" $exec_output] then {
+     fail $test7
+ } else {
+--- binutils.orig/ld/testsuite/ld-shared/shared.exp	2021-03-04 16:23:57.794940449 +0000
++++ binutils-2.35.1/ld/testsuite/ld-shared/shared.exp	2021-03-04 16:45:21.198173157 +0000
+@@ -245,6 +245,7 @@ if ![ld_compile "$CC $CFLAGS $SHCFLAG" $
+ 	    setup_xfail "arm*-*-linux*"
+ 	}
+ 	setup_xfail "aarch64*-*-linux*"
++	setup_xfail "i*86-*-linux*"
+ 	shared_test shnp "shared (non PIC)" mainnp.o sh1np.o sh2np.o shared
+ 
+ 	# Test ELF shared library relocations with a non-zero load
+@@ -273,6 +274,7 @@ if ![ld_compile "$CC $CFLAGS $SHCFLAG" $
+ 	setup_xfail "aarch64*-*-linux*"
+ 	# Solaris defaults to -z text.
+ 	setup_xfail "*-*-solaris2*"
++	setup_xfail "i*86-*-linux*"
+ 	shared_test shnp "shared (non PIC, load offset)" \
+ 		mainnp.o sh1np.o sh2np.o shared \
+ 		"-Wl,-T,$srcdir/$subdir/elf-offset.ld,--hash-style=sysv"
+@@ -326,6 +328,7 @@ if ![ld_compile "$CC $CFLAGS $SHCFLAG $p
+ 		setup_xfail "arm*-*-linux*"
+ 	    }
+ 	    setup_xfail "aarch64*-*-linux*"
++	    setup_xfail "i*86-*-linux*"
+ 	    shared_test shmpnp "shared (PIC main, non PIC so)" mainp.o sh1np.o sh2np.o shared
+ 	}
+     } else {
+--- binutils.orig/ld/testsuite/ld-elfvsb/elfvsb.exp	2021-03-05 09:25:45.023250161 +0000
++++ binutils-2.35.1/ld/testsuite/ld-elfvsb/elfvsb.exp	2021-03-05 09:33:36.866978952 +0000
+@@ -347,7 +347,6 @@ proc visibility_run {visibility} {
+ 		 || [ string match $visibility "protected_weak" ]
+ 		 || [ string match $visibility "normal" ] } {
+ 		setup_xfail "powerpc-*-linux*"
+-		setup_xfail "s390x-*-linux*"
+ 		if { [istarget sparc*-*-linux*] && [is_elf64 $tmpdir/mainnp.o] } {
+ 		    setup_xfail "sparc*-*-linux*"
+ 		}
